# Generated by Django 6.1 on 2026-09-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0002_remove_outboxevent_idx_outbox_status_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='target_type',
            field=models.CharField(choices=[('user', 'User'), ('tenant', 'Tenant'), ('conversation', 'Conversation')], help_text="Explicit delivery target type. NEVER null. 'user'         → channel group: user.{target_id} 'tenant'       → channel group: tenant.{target_id} 'conversation' → channel group: conversation.{target_id} Tenant-wide and conversation events require explicit authorization at dispatch time.", max_length=20),
        ),
    ]
