# Generated by Django 6.1 on 2026-09-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0003_alter_did_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='did',
            name='name',
            field=models.CharField(blank=True, default='', help_text="Human-readable name or label for this DID (e.g. 'Main Line', 'Support').", max_length=255),
        ),
    ]
