# Generated by Django 6.1 on 2026-09-02 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0004_did_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='did',
            name='calling_enabled',
        ),
        migrations.RemoveField(
            model_name='did',
            name='messaging_enabled',
        ),
    ]
