# Generated by Django 6.1 on 2026-09-10 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0005_remove_did_calling_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Access Group',
                'verbose_name_plural': 'Access Groups',
                'db_table': 'access_groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AccessGroupEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_group_entries', to='dids.did')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='dids.accessgroup')),
                ('department', models.ForeignKey(blank=True, help_text='Leave blank to grant all departments on this DID.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_group_entries', to='dids.department')),
            ],
            options={
                'verbose_name': 'Access Group Entry',
                'verbose_name_plural': 'Access Group Entries',
                'db_table': 'access_group_entries',
                'indexes': [models.Index(fields=['group'], name='idx_agentry_group'), models.Index(fields=['did'], name='idx_agentry_did')],
                'constraints': [models.UniqueConstraint(fields=('group', 'did', 'department'), name='uq_access_group_entry')],
            },
        ),
        migrations.CreateModel(
            name='TLGroupAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tl_access_grants', to='dids.accessgroup')),
                ('user', models.ForeignKey(help_text='The Team Lead being granted log visibility.', on_delete=django.db.models.deletion.CASCADE, related_name='tl_group_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'TL Group Access',
                'verbose_name_plural': 'TL Group Access',
                'db_table': 'tl_group_access',
                'indexes': [models.Index(fields=['user'], name='idx_tlaccess_user'), models.Index(fields=['group'], name='idx_tlaccess_group')],
                'constraints': [models.UniqueConstraint(fields=('user', 'group'), name='uq_tl_group_access')],
            },
        ),
        migrations.CreateModel(
            name='UserDIDDepartmentAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('department', models.ForeignKey(help_text='The department the caller works under for this DID.', on_delete=django.db.models.deletion.PROTECT, related_name='user_did_assignments', to='dids.department')),
                ('did', models.ForeignKey(help_text='The DID the caller works.', on_delete=django.db.models.deletion.CASCADE, related_name='user_department_assignments', to='dids.did')),
                ('user', models.ForeignKey(help_text='The caller being assigned to work this DID under this department.', on_delete=django.db.models.deletion.CASCADE, related_name='did_department_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User DID Department Assignment',
                'verbose_name_plural': 'User DID Department Assignments',
                'db_table': 'user_did_department_assignments',
                'indexes': [models.Index(fields=['user'], name='idx_uddassign_user'), models.Index(fields=['did'], name='idx_uddassign_did'), models.Index(fields=['department'], name='idx_uddassign_department')],
                'constraints': [models.UniqueConstraint(fields=('user', 'did', 'department'), name='uq_user_did_department_assignment')],
            },
        ),
    ]
