# Generated by Django 6.1 on 2026-10-01 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0007_department_hierarchy_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdidteamassignment',
            name='team',
            field=models.ForeignKey(help_text='The team the caller works under for this DID.', on_delete=django.db.models.deletion.CASCADE, related_name='user_did_assignments', to='dids.team'),
        ),
    ]
