# Generated by Django 6.1 on 2026-10-01 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0008_alter_userdidteamassignment_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'accounts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Division',
                'verbose_name_plural': 'Divisions',
                'db_table': 'divisions',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserDIDDivisionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
            ],
            options={
                'verbose_name': 'User DID Division Assignment',
                'verbose_name_plural': 'User DID Division Assignments',
                'db_table': 'user_did_division_assignments',
            },
        ),
        migrations.RemoveIndex(
            model_name='userdidteamassignment',
            name='idx_udtassign_user',
        ),
        migrations.RemoveIndex(
            model_name='userdidteamassignment',
            name='idx_udtassign_did',
        ),
        migrations.RemoveIndex(
            model_name='userdidteamassignment',
            name='idx_udtassign_team',
        ),
        migrations.RemoveConstraint(
            model_name='userdidteamassignment',
            name='uq_user_did_team_assignment',
        ),
        migrations.RemoveConstraint(
            model_name='accessgroupentry',
            name='uq_access_group_entry',
        ),
        migrations.RemoveConstraint(
            model_name='accessgroupentry',
            name='uq_access_group_entry_department',
        ),
        migrations.AddField(
            model_name='did',
            name='account',
            field=models.ForeignKey(blank=True, help_text='The billing/client account this DID is grouped under (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dids', to='dids.account'),
        ),
        migrations.AddField(
            model_name='accessgroupentry',
            name='division',
            field=models.ForeignKey(blank=True, help_text='Leave blank to grant all divisions on the DID(s) named above.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_group_entries', to='dids.division'),
        ),
        migrations.AddConstraint(
            model_name='accessgroupentry',
            constraint=models.UniqueConstraint(fields=('group', 'did', 'division'), name='uq_access_group_entry'),
        ),
        migrations.AddConstraint(
            model_name='accessgroupentry',
            constraint=models.UniqueConstraint(fields=('group', 'department', 'division'), name='uq_access_group_entry_department'),
        ),
        migrations.AddField(
            model_name='userdiddivisionassignment',
            name='did',
            field=models.ForeignKey(help_text='The DID the caller works.', on_delete=django.db.models.deletion.CASCADE, related_name='user_division_assignments', to='dids.did'),
        ),
        migrations.AddField(
            model_name='userdiddivisionassignment',
            name='division',
            field=models.ForeignKey(help_text='The division the caller works under for this DID.', on_delete=django.db.models.deletion.CASCADE, related_name='user_did_assignments', to='dids.division'),
        ),
        migrations.AddField(
            model_name='userdiddivisionassignment',
            name='user',
            field=models.ForeignKey(help_text='The caller being assigned to work this DID under this division.', on_delete=django.db.models.deletion.CASCADE, related_name='did_division_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userdidteamassignment',
            name='did',
        ),
        migrations.RemoveField(
            model_name='userdidteamassignment',
            name='team',
        ),
        migrations.RemoveField(
            model_name='userdidteamassignment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='accessgroupentry',
            name='team',
        ),
        migrations.AddIndex(
            model_name='userdiddivisionassignment',
            index=models.Index(fields=['user'], name='idx_uddassign_user'),
        ),
        migrations.AddIndex(
            model_name='userdiddivisionassignment',
            index=models.Index(fields=['did'], name='idx_uddassign_did'),
        ),
        migrations.AddIndex(
            model_name='userdiddivisionassignment',
            index=models.Index(fields=['division'], name='idx_uddassign_division'),
        ),
        migrations.AddConstraint(
            model_name='userdiddivisionassignment',
            constraint=models.UniqueConstraint(fields=('user', 'did', 'division'), name='uq_user_did_division_assignment'),
        ),
        migrations.DeleteModel(
            name='UserDIDTeamAssignment',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
