# Generated by Django 6.1 on 2026-10-01 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0009_account_division_userdiddivisionassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userdiddivisionassignment',
            name='uq_user_did_division_assignment',
        ),
        migrations.AddField(
            model_name='userdiddivisionassignment',
            name='department',
            field=models.ForeignKey(blank=True, help_text="The department this caller works this DID under (optional). Leave blank to use the DID's own department.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_did_division_assignments', to='dids.department'),
        ),
        migrations.AddIndex(
            model_name='userdiddivisionassignment',
            index=models.Index(fields=['department'], name='idx_uddassign_department'),
        ),
        migrations.AddConstraint(
            model_name='userdiddivisionassignment',
            constraint=models.UniqueConstraint(fields=('user', 'did', 'division', 'department'), name='uq_user_did_division_assignment'),
        ),
    ]
