# Generated by Django 6.1 on 2026-09-01 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0003_remove_extension_idx_extension_tenant_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extension',
            name='sip_server',
        ),
    ]
