# Generated by Django 6.1 on 2026-09-14 15:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('source_url', models.URLField(help_text='The original Telnyx/sender-supplied URL this was downloaded from.', max_length=2000)),
                ('file_path', models.CharField(help_text='Path on disk, relative to MESSAGING_MEDIA_ROOT.', max_length=512)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='messaging.message')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message'], name='messaging_m_message_404b0e_idx')],
            },
        ),
    ]
