# Generated by Django 6.1 on 2026-09-03 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_tenant_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('directory_type', models.CharField(choices=[('company', 'Company Directory'), ('personal', 'Personal Directory')], db_index=True, default='personal', help_text='Directory scope: company (tenant-wide) or personal (user-private).', max_length=20)),
                ('first_name', models.CharField(help_text='Contact first name (required).', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', help_text='Contact last name (optional).', max_length=150)),
                ('email', models.EmailField(blank=True, help_text='Contact email address (optional).', max_length=254, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Free-form notes about the contact.')),
                ('is_favorite', models.BooleanField(default=False, help_text='Whether this contact is pinned/favorited by the user.')),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created this contact entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='The user who owns this personal contact. Null for company directory contacts.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_contacts', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(help_text='Tenant that owns this contact record.', on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
                'ordering': ['first_name', 'last_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('number', models.CharField(db_index=True, help_text='Phone number or extension (e.g. +12025550199, 1001).', max_length=50)),
                ('label', models.CharField(default='Mobile', help_text='Label for this number (e.g. Mobile, Work, Home, Office, Custom).', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Indicates whether this is the primary dialing number for the contact.')),
                ('contact', models.ForeignKey(help_text='Contact to which this phone number belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'Contact Number',
                'verbose_name_plural': 'Contact Numbers',
                'db_table': 'contact_numbers',
                'ordering': ['-is_primary', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'directory_type'], name='idx_contact_tenant_dir'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['tenant', 'owner'], name='idx_contact_tenant_owner'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['first_name', 'last_name'], name='idx_contact_names'),
        ),
        migrations.AddIndex(
            model_name='contactnumber',
            index=models.Index(fields=['contact', 'is_primary'], name='idx_contactnum_primary'),
        ),
        migrations.AddIndex(
            model_name='contactnumber',
            index=models.Index(fields=['number'], name='idx_contactnum_number'),
        ),
    ]
