# Generated by Django 6.1 on 2026-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='sip_domain',
            field=models.CharField(blank=True, default='', help_text="Default SIP domain / registrar host for all users in this tenant (e.g. 'sip.example.com' or 'pbx.tenant.com').", max_length=255),
        ),
    ]
