# Generated by Django 6.1 on 2026-09-03 15:18

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_tenant_sip_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='features',
            field=models.JSONField(default=apps.tenants.models.default_tenant_features, help_text='Dict of enabled features for this tenant. Valid keys: calling, messaging, fax. Values must be booleans. Voicemail is automatically enabled if calling is enabled. Example: {"calling": true, "messaging": true, "fax": false}', validators=[apps.tenants.models.validate_tenant_features]),
        ),
    ]
