# Generated by Django 6.1 on 2026-09-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_alter_tenant_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='telnyx_messaging_profile_id',
            field=models.CharField(blank=True, default='', help_text='Telnyx Messaging Profile ID used to send SMS/MMS on behalf of this tenant.', max_length=64),
        ),
    ]
