# Generated by Django 6.1 on 2026-09-11 16:46

import apps.downloads.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesktopDownloadToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('token', models.CharField(default=apps.downloads.models._generate_token, editable=False, help_text='Opaque token embedded in the download URL. Not the update-server PUBLISH_TOKEN.', max_length=64, unique=True)),
                ('os', models.CharField(choices=[('win', 'Windows'), ('mac', 'macOS'), ('linux', 'Linux')], max_length=8)),
                ('first_used_at', models.DateTimeField(blank=True, help_text='Set on first fetch; the 2-hour validity window is measured from this.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desktop_download_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='downloads_d_token_244d4b_idx')],
            },
        ),
    ]
