# Generated by Django 6.1 on 2026-09-09 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_tenant_telnyx_messaging_profile_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FaxTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='UTC timestamp of record creation.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='UTC timestamp of last record update.')),
                ('fax_file_uuid', models.CharField(help_text='FreeSWITCH fax transmission UUID (fax_file_uuid) this record applies to.', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=16)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User (with an extension) this fax has been assigned to for review.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_faxes', to=settings.AUTH_USER_MODEL)),
                ('status_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fax_tags', to='tenants.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'fax_file_uuid'], name='common_faxt_tenant__031260_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'fax_file_uuid'), name='uniq_fax_tag_per_transmission')],
            },
        ),
    ]
