# Generated by Django 6.1 on 2026-09-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_idx_user_vmboxes_gin_user_idx_user_faxboxes_gin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sip_domain',
            field=models.CharField(blank=True, default='', help_text="Custom SIP domain / registrar host for this user. If blank, automatically inherits the tenant's default sip_domain.", max_length=255),
        ),
    ]
