# Generated by Django 6.1 on 2026-09-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_team_lead',
            field=models.BooleanField(db_index=True, default=False, help_text="Marks this user as a Team Lead. Independent of role — a Team Lead is typically an 'admin' but this is not enforced. Controls eligibility for TLGroupAccess grants (call-log/report visibility scoped by DID and Department); does not itself grant any access."),
        ),
    ]
