# Generated by Django 6.1 on 2026-09-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_team_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_admins',
            field=models.BooleanField(default=False, help_text="Grants this admin the ability to create other 'admin'-role users. Settable only by a superadmin. Superadmins can always create admins regardless of this flag."),
        ),
    ]
