# Generated by Django 6.1 on 2026-09-11 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dids', '0007_department_hierarchy_rename'),
        ('users', '0008_user_can_create_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='The department this user works under (global to the user, not tied to any specific DID). Drives TL log-visibility resolution together with the DIDs the user is assigned (UserDID).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='dids.department'),
        ),
    ]
