# Generated by Django 6.1 on 2026-10-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_create_admins',
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_team_lead',
            field=models.BooleanField(db_index=True, default=False, help_text="Marks this user as a Team Lead. Independent of role — a Team Lead is typically an 'admin' but this is not enforced. Controls eligibility for TLGroupAccess grants (call-log/report visibility scoped by DID and Division); does not itself grant any access."),
        ),
    ]
