# Generated by Django 6.1 on 2026-10-01 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_can_create_admins_remove_user_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4).', primary_key=True, serialize=False)),
                ('to_email', models.EmailField(db_index=True, help_text='Recipient address the email was sent to.', max_length=254)),
                ('subject', models.CharField(help_text='Subject line of the sent email.', max_length=255)),
                ('template', models.CharField(blank=True, help_text="Name of the email task/template that generated this send (e.g. 'welcome_email').", max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], db_index=True, help_text='Whether the send succeeded or failed.', max_length=10)),
                ('error', models.TextField(blank=True, help_text='Error message if the send failed. Empty on success.')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='UTC timestamp when this send was attempted.')),
                ('user', models.ForeignKey(blank=True, help_text='The user this email concerns, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'db_table': 'email_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
