# Generated by Django 6.1 on 2026-10-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_emaillog'),
        ('users', '0011_password_reset_token'),
    ]

    operations = [
    ]
