# Generated by Django 6.1 on 2026-10-06 14:33

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_0011_emaillog_0011_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='features',
            field=models.JSONField(blank=True, default=dict, help_text="Per-user feature overrides. Keys: 'calling', 'messaging', 'fax'. Empty dict (default) inherits from tenant. Set a key to False to disable for this user; True cannot exceed what the tenant allows.", validators=[apps.users.validators.validate_user_features]),
        ),
    ]
